/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#000666',
        'primary-container': '#1a237e',
        'primary-fixed': '#e0e0ff',
        'primary-fixed-dim': '#bdc2ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#8690ee',
        'on-primary-fixed': '#000767',
        'on-primary-fixed-variant': '#343d96',
        'inverse-primary': '#bdc2ff',
        secondary: '#005ac1',
        'secondary-container': '#4d8efe',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00285c',
        'on-secondary-fixed': '#001a41',
        'on-secondary-fixed-variant': '#004494',
        tertiary: '#2d1500',
        'tertiary-container': '#4c2600',
        'tertiary-fixed': '#ffdcc2',
        'tertiary-fixed-dim': '#ffb77a',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#df8017',
        'on-tertiary-fixed': '#2e1500',
        'on-tertiary-fixed-variant': '#6d3a00',
        background: '#fbf8ff',
        surface: '#fbf8ff',
        'surface-dim': '#dbd9e1',
        'surface-bright': '#fbf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2fb',
        'surface-container': '#efecf5',
        'surface-container-high': '#eae7ef',
        'surface-container-highest': '#e4e1ea',
        'surface-variant': '#e4e1ea',
        'surface-tint': '#4c56af',
        'on-background': '#1b1b21',
        'on-surface': '#1b1b21',
        'on-surface-variant': '#454652',
        'inverse-surface': '#303036',
        'inverse-on-surface': '#f2eff8',
        outline: '#767683',
        'outline-variant': '#c6c5d4',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['"Public Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        unit: '4px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'container-max': '1280px',
      },
      boxShadow: {
        card: '0px 4px 20px rgba(26,35,126,0.05)',
        'card-hover': '0px 8px 30px rgba(26,35,126,0.08)',
      },
    },
  },
  plugins: [],
};
